name: Go release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'amd64', 'arm64' ]
        os: [ 'linux' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o rfplayer.${{ matrix.os }}-${{ matrix.arch }} cmd/gorfplayer/gorfplayer.go

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: env GOOS=${{matrix.os}} GOARCH=${{matrix.arch}}
          path: rfplayer.${{ matrix.os }}-${{ matrix.arch }}

# no test for now
#      - name: Test
#run: go test -v ./...
